{
 "title": "GKE Pods Usage Status",
 "tags": [
  "Compute",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Container Memory Used (evictable) / Pod",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "aliasBy": "{{resource.label.pod_name}}",
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "external.googleapis.com/prometheus/kube_node_status_capacity_pods",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     },
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "resource.label.cluster_name",
       "=",
       "prod-cluster",
       "AND",
       "resource.label.namespace_name",
       "=",
       "$namespace",
       "AND",
       "metric.label.memory_type",
       "=",
       "evictable",
       "AND",
       "metric.type",
       "=",
       "kubernetes.io/container/memory/used_bytes"
      ],
      "groupBys": [ "resource.label.pod_name" ],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "Container Memory Used (not - evictable) / Pod",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "aliasBy": "{{resource.label.pod_name}}",
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "external.googleapis.com/prometheus/kube_node_status_capacity_pods",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     },
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "resource.label.cluster_name",
       "=",
       "prod-cluster",
       "AND",
       "resource.label.namespace_name",
       "=",
       "$namespace",
       "AND",
       "metric.label.memory_type",
       "=",
       "non-evictable",
       "AND",
       "metric.type",
       "=",
       "kubernetes.io/container/memory/used_bytes"
      ],
      "groupBys": [ "resource.label.pod_name" ],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "Container CPU Used / App",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aliasBy": "{{resource.label.pod_name}}",
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "external.googleapis.com/prometheus/kube_node_status_capacity_pods",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     },
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "resource.label.cluster_name",
       "=",
       "prod-cluster",
       "AND",
       "resource.label.namespace_name",
       "=",
       "$namespace",
       "AND",
       "metric.type",
       "=",
       "kubernetes.io/container/cpu/core_usage_time"
      ],
      "groupBys": [ "resource.label.pod_name" ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "Network (bytes received) / Service",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aliasBy": "{{metadata.system_labels.service_name}}",
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "external.googleapis.com/prometheus/kube_node_status_capacity_pods",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     },
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.cluster_name",
       "=",
       "prod-cluster",
       "AND",
       "resource.label.namespace_name",
       "=",
       "$namespace",
       "AND",
       "metric.type",
       "=",
       "kubernetes.io/pod/network/received_bytes_count"
      ],
      "groupBys": [
       "metadata.system_labels.service_name"
      ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "$project"
     }
    }
   ]
  }
 ]
}