{
 "title": "GKE Nodes Usage Status",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "aliasBy": "{{resource.label.node_name}}",
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "external.googleapis.com/prometheus/kube_node_status_capacity_pods",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     },
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "resource.label.cluster_name",
       "=",
       "prod-cluster",
       "AND",
       "metric.type",
       "=",
       "kubernetes.io/node/memory/used_bytes"
      ],
      "groupBys": [ "resource.label.node_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "Nodes - CPU Usage Time",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aliasBy": "{{resource.label.node_name}}",
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "external.googleapis.com/prometheus/kube_node_status_capacity_pods",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     },
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "resource.label.cluster_name",
       "=",
       "prod-cluster",
       "AND",
       "metric.type",
       "=",
       "kubernetes.io/node/cpu/core_usage_time"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "Nodes - Network (bytes received) ",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aliasBy": "{{resource.label.node_name}}",
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "external.googleapis.com/prometheus/kube_node_status_capacity_pods",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     },
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "resource.label.cluster_name",
       "=",
       "prod-cluster",
       "AND",
       "metric.type",
       "=",
       "kubernetes.io/node/network/received_bytes_count"
      ],
      "groupBys": [ "resource.label.node_name" ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "Nodes - Disk Usage",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "resource.label.cluster_name",
       "=",
       "prod-cluster",
       "AND",
       "metric.type",
       "=",
       "kubernetes.io/node/ephemeral_storage/total_bytes"
      ],
      "groupBys": [ "resource.label.node_name" ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "none",
      "projectName": "$project"
     }
    },
    { "expression": "($A * 100) /  $B", "type": "math" }
   ]
  }
 ]
}