{
 "title": "K8 Pods Resources Usage Overview",
 "description": "Kubernetes_ POD Overview",
 "tags": [
  "kubernetes",
  "pods"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "POD Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage - $pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "repeat": "pod",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container)(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", image!=\"\", container!=\"POD\", image!=\"\"}[2m]))",
     "legendFormat": "Current: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\", container!=\"POD\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{pod=~\"$pod\", container!=\"POD\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "Memory Usage - $pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "repeat": "pod",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by(container) (container_memory_working_set_bytes{pod=~\"$pod\", container!=\"POD\",container!=\"\",image!=\"\"})",
     "legendFormat": "Current: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{pod=~\"$pod\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "Network - $pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "repeat": "pod",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate (container_network_transmit_bytes_total{pod=~\"$pod\",interface=~\"eth0|ens.*\"}[5m])",
     "legendFormat": "TX : {{ pod }}"
    },
    {
     "expr": "rate (container_network_receive_bytes_total{pod=~\"$pod\",interface=~\"eth0|ens.*\"}[5m])",
     "legendFormat": "RX : {{ pod }}"
    }
   ]
  }
 ]
}