{
 "title": "K8s Deployments Status",
 "description": "Kubernetes Deployments Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "deployment_namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_deployment_metadata_generation, namespace)"
    }
   },
   {
    "name": "deployment_name",
    "label": "Deployment",
    "query": {
     "query": "label_values(kube_deployment_metadata_generation{namespace=\"$deployment_namespace\"}, deployment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Selected Deployment Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Desired Replicas",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "max(kube_deployment_spec_replicas{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)"
      }
     ]
    },
    {
     "title": "Available Replicas",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "min(kube_deployment_status_replicas_available{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)"
      }
     ]
    },
    {
     "title": "Observed Generation",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "max(kube_deployment_status_observed_generation{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)"
      }
     ]
    },
    {
     "title": "Metadata Generation",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "max(kube_deployment_metadata_generation{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)"
      }
     ]
    },
    {
     "title": "Replicas",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max(kube_deployment_status_replicas{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
       "legendFormat": "Current"
      },
      {
       "expr": "min(kube_deployment_status_replicas_available{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
       "legendFormat": "Available"
      },
      {
       "expr": "max(kube_deployment_status_replicas_unavailable{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
       "legendFormat": "Unavailable"
      },
      {
       "expr": "min(kube_deployment_status_replicas_updated{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
       "legendFormat": "Updated"
      },
      {
       "expr": "max(kube_deployment_spec_replicas{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
       "legendFormat": "Desired"
      }
     ]
    }
   ]
  },
  { "title": "All Deployments Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "$deployment_name",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "repeat": "deployment_name",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  }
 ]
}